//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJenkins.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetails
    {
        public string Employee_Name { get; set; }
        public int Employee_Number { get; set; }
    }
}
