//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJenkins.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SampleEntities : DbContext
    {
        public SampleEntities()
            : base("name=SampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuildVersion> BuildVersion { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<EmployeeDetails> EmployeeDetails { get; set; }
    
        public virtual ObjectResult<sp_buildversion_Result> sp_buildversion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_buildversion_Result>("sp_buildversion");
        }
    
        public virtual ObjectResult<sp_viewemployee_Result> sp_viewemployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewemployee_Result>("sp_viewemployee");
        }
    }
}
